<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>archive</string>
  <key>fileTypes</key>
  <array>
    <string>zip</string>
    <string>rar</string>
    <string>7z</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string></string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>archive</string>
</dict>
</plist>
